### ISSUE TITLE
Jinja template throws error name with alternatives

### ISSUE THREAD

**Issue by schizza** [home-assistant/intents#1046]
In _`fixtures` I have defined light as:
```
entities:
  - name: "(Lamp(a|y|u)|lampičk(a|y|u)|světl(o|a)) ložnice"
    id: light.bedroom_lamp
    area: bedroom
    attributes:
      device_class: light
    state:
      in: "zapnutá"
      out: "on"
```

When I ask a state for this light an error will occur:
```
python3 -m script.intentfest parse --language cs --sentence "v jakém stavu je lampička ložnice?"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspaces/intents/script/intentfest/__main__.py", line 29, in <module>
    sys.exit(main())
  File "/workspaces/intents/script/intentfest/__main__.py", line 24, in main
    return module.run()
  File "/workspaces/intents/script/intentfest/parse.py", line 89, in run
    render_response(response_template, result, matched, unmatched)
  File "/workspaces/intents/shared/__init__.py", line 156, in render_response
    return env.from_string(response_template).render(
  File "/home/vscode/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/vscode/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'None' has no attribute 'state_with_unit'
```

If I change name of the entity to simple `lampička ložnice` everything will proceed without error.
Alternatives are needed as for other commands such as turn on or off, dimming or changing color - we are using other grammar case.

**Comment by synesthesiam** [comment]
Do you have a sentence template I can use to test this with?
Also, why is the `device_class` of the test entity set to `light`?

**Comment by schizza** [comment]
> Do you have a sentence template I can use to test this with?
> Also, why is the `device_class` of the test entity set to `light`?

```
language: cs
intents:
  HassGetState:
    data:
      - sentences:
          - "v jakém stavu [<area>] je {name}"
        response: one

      - sentences:
          - "Svítí {name} [<area>]"
        response: one_light
        slots:
          domain: light


      - sentences:
          - "je {name} [<area>] {on_off_states:state}"
        response: one_yesno
        excludes_context:
          domain:
            - cover

      - sentences:
          - "jsou někter(é|á|ý) {on_off_domains:domain} [<area>] {on_off_states:state}"
        response: any

      - sentences:
          - "jsou všechn(a|y) [<area>] {on_off_domains:domain} {on_off_states:state}"
        response: all

      - sentences:
          - "kter(á|é) {on_off_domains:domain} (jsou|je) [<area>] {on_off_states:state}"
        response: which

      - sentences:
          - "kolik {on_off_domains:domain} (je|jsou) [<area>] {on_off_states:state}"
        response: how_many
```

**Comment by synesthesiam** [comment]
Should be fixed by: https://github.com/home-assistant/intents/pull/1076
