### ISSUE TITLE
Unexpected error with lock intent

### ISSUE THREAD

**Issue by froman753** [home-assistant/intents#1347]
I have a Schlage Z-wave lock that is exposed to the Cloud Assistant with the alias "front door", but attempting to lock or unlock the door  ("unlock the front door") with the Assist gives me "An unexpected error occurred while handling the intent".

This is what the debugger gives me:

Engine                            homeassistant
Language                        en
Input                                unlock the front door
Response type                 error
Error code                        failed_to_handle
Raw
<pre>intent_output:  
  response:  
    speech:  
      plain:  
        speech: An unexpected error occurred while handling the intent  
        extra_data: null  
    card: {}  
    language: en  
    response_type: error  
    data:  
      code: failed_to_handle  
  conversation_id: null</pre>

Appreciate any help with anything I could be doing wrong.

**Comment by steffenrapp** [comment]
Same here with a different lock in German. The response is correct if an area is added but the lock won't open in that case ... don't understand it.

**Comment by jparchem** [comment]
Also seeing this as well.  This was part of the stack trace:

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 193, in async_process
    intent_response = await intent.async_handle(
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 96, in async_handle
    result = await handler.async_handle(intent)
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 417, in async_handle
    response = await self.async_handle_states(intent_obj, states, area)
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 466, in async_handle_states
    raise IntentHandleError(
homeassistant.helpers.intent.IntentHandleError: Failed to call turn_on for: ['lock.mydoor']

**Comment by tetele** [comment]
This is a bug in HA, but I don't have the rights to move it there. I've created a PR to fix it here https://github.com/home-assistant/core/pull/93231

**Comment by clearwave1** [comment]
I have the same issue with a Yale Z-wave lock. Looking forward to the fix as I was surprised this wasn't caught in the initial launch of Assist.

In English, we should support unlock/open and lock/close terminology.

**Comment by GNeras** [comment]
I have this problem too. I also want to point out the fact that locks have 3 services: lock.lock, lock.unlock and lock.open (this will unlock the lock if needed and unlatch), so we should be careful about which words should trigger each service.
