### ISSUE TITLE
Switch Domain not Working

### ISSUE THREAD

**Issue by Johnson145** [home-assistant/intents#1455]
It looks like I just can't interact with entities of the _switch_ domain. That should work already, shouldn't it? Other domains are working just fine.

Whenever I try to enable or disable a switch, Assist responds with

> An unexpected error occurred while handling the intent

Furthermore, the log reveals the following:

```
2023-07-21 17:46:22.345 ERROR (MainThread) [homeassistant.components.conversation.default_agent] Intent handling error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/conversation/default_agent.py", line 216, in async_process
    intent_response = await intent.async_handle(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 106, in async_handle
    result = await handler.async_handle(intent)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/intent.py", line 423, in async_handle
    raise IntentHandleError(
homeassistant.helpers.intent.IntentHandleError: No entities matched for: name=Nachtsound, area=None, domains=None, device_classes=None
```

Tested English and German.

Of course, I also double checked that there is an entity called `Nachtsound`.

If I try the same sentence with an actually unknown entity name, Assist instead responds with:

> Sorry, I couldn't understand that

Thus, it actually seems to find the entity, although the log suggests something else.

If I use the new Assist Developer Tool, I get this:

```yml
intent:
  name: HassTurnOn
entities:
  name:
    name: name
    value: Nachtsound
    text: nachtsound
targets: {}
```

**Comment by tetele** [comment]
What sentence are you using?

**Comment by Johnson145** [comment]
In English, for instance `Turn on the Nachtsound.`.

Similar sentences fail the same way, too.

**Comment by tetele** [comment]
Is it only for this particular light? Does the problem persist with other lights as well?

Is the switch [exposed](https://www.home-assistant.io/voice_control/voice_remote_expose_devices/) to Assist?

**Comment by Johnson145** [comment]
Tested again with multiple entities.

> Is it only for this particular light? Does the problem persist with other lights as well?

I found one integration for which the switches work correctly. The switches of at least two other integrations consistently produce the error though.

> Is the switch [exposed](https://www.home-assistant.io/voice_control/voice_remote_expose_devices/) to Assist?

Yes, all of them were exposed. I guess that part is working fine. If I disable the exposure, the error message changes to 

> Sorry, I couldn't understand that

Error still occurs on the latest HA version.

**Comment by tetele** [comment]
@pako-github could you please paste the log message?

**Comment by tetele** [comment]
That's exactly what I wanted to see, but I see nothing wrong with your setup, which doesn't help with troubleshooting.

Are all your `switch`es behaving the same?

**Comment by pako-github** [comment]
No, other `switch` are working (although not as intended, but this is probably a bug in the respective integration). It is strange, that the wifi switch is working without problems if I use it with a card on a dashboard.

**Comment by Johnson145** [comment]
@tetele You could be right. At least in my case, `Nachtsound` is also "slow" in that means. It's toggling the night sound mode of a Sonos speaker. I.e. it probably needs to wait for a (HTTP?) request sent by the [Sonos integration](https://www.home-assistant.io/integrations/sonos). From a user perspective, toggling the entity in Home Assistant does result in an "almost immediate reaction" on the Sonos speaker, but of course it's not a synchronous programming action.

**Comment by tetele** [comment]
@synesthesiam do you have any ideas here?

**Comment by tetele** [comment]
Root cause: https://github.com/home-assistant/architecture/discussions/740

**Comment by pako-github** [comment]
Is there any work around maybe?

**Comment by tetele** [comment]
No, unfortunately
