### ISSUE TITLE
Setup did not work for me

### ISSUE THREAD

**Issue by lellky** [home-assistant/intents#76]
I added `pip install -r requirements.txt` to the readme earlier today, but it got removed again. I see that the setup should do it, but when I ran the setup and then added a new language I got this:

```
lellky@MacBook-Air intents % python3 -m script.intentfest add_language sv
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/lellky/Projects/intents/script/intentfest/__main__.py", line 29, in <module>
    sys.exit(main())
  File "/Users/lellky/Projects/intents/script/intentfest/__main__.py", line 23, in main
    module = importlib.import_module(f".{args.action}", "script.intentfest")
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/lellky/Projects/intents/script/intentfest/add_language.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by synesthesiam** [comment]
Does the `source` command for activating the virtual environment work on a Mac?

**Comment by balloob** [comment]
Did you activate your virtual environment as per the [development section](https://github.com/home-assistant/intents#development) in the README:

> Before developing, always activate your virtual environment with `source venv/bin/activate`.

**Comment by lellky** [comment]
Yes, the source command seems to work. Yes, I activated the virtual env.

Weird. Now it actually works! ✅ 

Following the Readme now gives this

```
lellky@Jonass-MacBook-Air intents % rm -rf venv
lellky@Jonass-MacBook-Air intents % ./script/setup
Creating virtual environment at /Users/lellky/Projects/intents/venv (Python 3.9.10)
Installing Python dependencies
Requirement already satisfied: pip in ./venv/lib/python3.9/site-packages (21.3.1)
Collecting pip
  Using cached pip-22.3.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.3.1
    Uninstalling pip-21.3.1:
      Successfully uninstalled pip-21.3.1
Successfully installed pip-22.3.1
Collecting wheel
  Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.9/site-packages (60.5.0)
Collecting setuptools
  Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 60.5.0
    Uninstalling setuptools-60.5.0:
      Successfully uninstalled setuptools-60.5.0
Successfully installed setuptools-65.6.3 wheel-0.38.4
Collecting hassil==0.1.2
  Using cached hassil-0.1.2-py3-none-any.whl
Collecting PyYAML==6.0
  Using cached PyYAML-6.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Collecting voluptuous==0.13.1
  Using cached voluptuous-0.13.1-py3-none-any.whl (29 kB)
Collecting black==22.12.0
  Using cached black-22.12.0-py3-none-any.whl (167 kB)
Collecting flake8==6.0.0
  Using cached flake8-6.0.0-py2.py3-none-any.whl (57 kB)
Collecting isort==5.11.3
  Using cached isort-5.11.3-py3-none-any.whl (117 kB)
Collecting mypy==0.991
  Using cached mypy-0.991-cp39-cp39-macosx_11_0_arm64.whl (10.0 MB)
Collecting pylint==2.15.9
  Using cached pylint-2.15.9-py3-none-any.whl (509 kB)
Collecting pytest==7.2.0
  Using cached pytest-7.2.0-py3-none-any.whl (316 kB)
Collecting dataclasses-json==0.5.7
  Using cached dataclasses_json-0.5.7-py3-none-any.whl (25 kB)
Collecting antlr4-python3-runtime==4.11.1
  Using cached antlr4_python3_runtime-4.11.1-py3-none-any.whl (144 kB)
Collecting click>=8.0.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting pathspec>=0.9.0
  Using cached pathspec-0.10.3-py3-none-any.whl (29 kB)
Collecting tomli>=1.1.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting typing-extensions>=3.10.0.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting platformdirs>=2
  Using cached platformdirs-2.6.0-py3-none-any.whl (14 kB)
Collecting mccabe<0.8.0,>=0.7.0
  Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting pycodestyle<2.11.0,>=2.10.0
  Using cached pycodestyle-2.10.0-py2.py3-none-any.whl (41 kB)
Collecting pyflakes<3.1.0,>=3.0.0
  Using cached pyflakes-3.0.1-py2.py3-none-any.whl (62 kB)
Collecting tomlkit>=0.10.1
  Using cached tomlkit-0.11.6-py3-none-any.whl (35 kB)
Collecting dill>=0.2
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting astroid<=2.14.0-dev0,>=2.12.13
  Using cached astroid-2.12.13-py3-none-any.whl (264 kB)
Collecting exceptiongroup>=1.0.0rc8
  Using cached exceptiongroup-1.0.4-py3-none-any.whl (14 kB)
Collecting packaging
  Using cached packaging-22.0-py3-none-any.whl (42 kB)
Collecting attrs>=19.2.0
  Using cached attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting typing-inspect>=0.4.0
  Using cached typing_inspect-0.8.0-py3-none-any.whl (8.7 kB)
Collecting marshmallow-enum<2.0.0,>=1.5.1
  Using cached marshmallow_enum-1.5.1-py2.py3-none-any.whl (4.2 kB)
Collecting marshmallow<4.0.0,>=3.3.0
  Using cached marshmallow-3.19.0-py3-none-any.whl (49 kB)
Collecting lazy-object-proxy>=1.4.0
  Using cached lazy_object_proxy-1.8.0-cp39-cp39-macosx_11_0_arm64.whl
Collecting wrapt<2,>=1.11
  Using cached wrapt-1.14.1-cp39-cp39-macosx_11_0_arm64.whl (35 kB)
Installing collected packages: voluptuous, mypy-extensions, iniconfig, antlr4-python3-runtime, wrapt, typing-extensions, tomlkit, tomli, PyYAML, pyflakes, pycodestyle, pluggy, platformdirs, pathspec, packaging, mccabe, lazy-object-proxy, isort, exceptiongroup, dill, click, attrs, typing-inspect, pytest, mypy, marshmallow, flake8, black, astroid, pylint, marshmallow-enum, dataclasses-json, hassil
Successfully installed PyYAML-6.0 antlr4-python3-runtime-4.11.1 astroid-2.12.13 attrs-22.2.0 black-22.12.0 click-8.1.3 dataclasses-json-0.5.7 dill-0.3.6 exceptiongroup-1.0.4 flake8-6.0.0 hassil-0.1.2 iniconfig-1.1.1 isort-5.11.3 lazy-object-proxy-1.8.0 marshmallow-3.19.0 marshmallow-enum-1.5.1 mccabe-0.7.0 mypy-0.991 mypy-extensions-0.4.3 packaging-22.0 pathspec-0.10.3 platformdirs-2.6.0 pluggy-1.0.0 pycodestyle-2.10.0 pyflakes-3.0.1 pylint-2.15.9 pytest-7.2.0 tomli-2.0.1 tomlkit-0.11.6 typing-extensions-4.4.0 typing-inspect-0.8.0 voluptuous-0.13.1 wrapt-1.14.1
OK
lellky@Jonass-MacBook-Air intents % source venv/bin/activate
(venv) lellky@Jonass-MacBook-Air intents % python3 -m script.intentfest validate
All good!
```
